# Generated by Django 4.2 on 2023-04-30 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='brand',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='name',
            new_name='nombre',
        ),
    ]
