# Generated by Django 4.2 on 2023-05-03 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_carrito_itemdecarrito_carrito_items_carrito_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdecarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemdecarrito',
            name='producto',
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemDeCarrito',
        ),
    ]
