# Generated by Django 4.2 on 2023-05-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_itemdecarrito_carrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalle',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='informacion del producto'),
        ),
    ]
