# Generated by Django 4.2 on 2023-04-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_contacto_duenio_animal_contacto_telefonico_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal',
            new_name='Mascota',
        ),
    ]
