# Generated by Django 4.2 on 2023-04-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_animal_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='contacto_telefonico',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='propietario',
        ),
    ]
