# Generated by Django 4.2 on 2023-04-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
