# Generated by Django 4.2 on 2023-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_infoextra_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoextra',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='infoextra',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='infoextra',
            name='email',
        ),
        migrations.RemoveField(
            model_name='infoextra',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='infoextra',
            name='telefono',
        ),
        migrations.AddField(
            model_name='infoextra',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
